export const CREATE_USER = "USER/CREATE_USER";
export const FETCH_SMALL_USERS = "USER/FETCH_SMALL_USERS";
export const FETCH_BIG_USERS = "USER/FETCH_BIG_USERS";
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
